_commit: v1.6.18-4-gf354859
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: cluster-secret-stores.yaml,network-policies.yaml
backups: false
helm: true
helmCrds: true
helmName: external-secrets
helmRelease: external-secrets
helmRepo: https://charts.external-secrets.io
helmValues: ''
helmVersion: ''
ingress: false
labels: 'app: external-secrets'
name: external-secrets
namespace: external-secrets
pvc: false
reloader: true
resources:
- deployments.yaml
- secrets.yaml
- services.yaml
service: false
serviceAccount: false
upstreamURL: https://external-secrets.io/
url: https://github.com/charlesthomas/homelab-external-secrets
