---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-external-secrets
commonLabels:
  app: external-secrets

resources:
- resources/cluster-secret-stores.yaml
- resources/deployments.yaml
- resources/namespaces.yaml
- resources/network-policies.yaml
- resources/secrets.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: external-secrets
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
helmCharts:
- name: external-secrets
  namespace: external-secrets
  includeCRDs: true
  releaseName: external-secrets
  repo: https://charts.external-secrets.io
