---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-external-secrets
commonLabels:
  app: external-secrets

resources:
- resources/cluster-secret-stores.yaml
- resources/deployments.yaml
- resources/namespaces.yaml
- resources/network-policies.yaml
- resources/secrets.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: external-secrets
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: external-secrets
      namespace: external-secrets
      annotations:
        gethomepage.dev/href: https://external-secrets.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: external-secrets
        gethomepage.dev/name: external-secrets
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
helmCharts:
- name: external-secrets
  includeCRDs: true
  namespace: external-secrets
  releaseName: external-secrets
  repo: https://charts.external-secrets.io
